### ISSUE TITLE
Running `gulp default` complains about `node-sass`

### ISSUE THREAD

**Issue by mikehostetler** [onenorth/gulp-browserify-kit#2]
I reinstalled node-sass several times, not sure how to fix this yet.

```console
± % gulp default                                                                                                       !812
[22:18:50] Using gulpfile ~/Clients/onenorth/gulp-browserify-kit/gulpfile.js
[22:18:50] Starting 'build'...
[22:18:50] Starting 'clean'...
[22:18:50] Finished 'clean' after 8.03 ms
[22:18:50] Starting 'templates'...
[22:18:50] Starting 'styles'...
[22:18:50] 'styles' errored after 50 ms
[22:18:50] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:21:11)
    at Object.<anonymous> (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:456:26)
[22:18:50] 'build' errored after 123 ms
[22:18:50] Error: [object Object]
    at formatError (/Users/mhostetler/.nvm/v0.10.32/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/mhostetler/.nvm/v0.10.32/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/Users/mhostetler/Clients/onenorth/gulp-browserify-kit/node_modules/run-sequence/index.js:55:4)
    at Gulp.emit (events.js:117:20)
[22:18:50] Finished 'templates' after 139 ms```

**Comment by askesian** [comment]
Did you run ```npm install``` after cloning the repo, but before you ran ```gulp default```?

**Comment by askesian** [comment]
If you run `npm install` after cloning the repository, `gulp-sass` should be installed since it is listed as a dev dependency in package.json. `Gulp-sass` has `node-sass` as a dependency, so `node-sass` should be installed when `gulp-sass` is installed.

**Comment by askesian** [comment]
Mike,

After thinking about this some more, this might have something to do w/ the way I was referencing the gulp binary in `package.json`. I've update the gulp reference to `gulp` instead of `./node_modules/.bin/gulp`. Would you mind pulling the latest updates and giving it a go? Sorry for the hassle.

**Comment by mikehostetler** [comment]
Sure, I'll give it a try.

**Comment by mikehostetler** [comment]
Yep, cloned it down and that worked!
